# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13u_vw7yCg0zTbdA9mI6YVHNCz4Qx2bSk
"""

import streamlit as st
import pandas as pd
import joblib
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score, matthews_corrcoef
import os

st.title("Classification Model Showcase")

# a. Dataset Upload (Test data only as per instructions)
uploaded_file = st.file_uploader("Upload Test CSV", type="csv")

if uploaded_file:
    data = pd.read_csv(uploaded_file)
    st.write("Dataset Preview:", data.head())

    # Assume the last column is the target for this demo
    X_test = data.iloc[:, :-1]
    y_test = data.iloc[:, -1]

    # b. Model Selection Dropdown
    model_option = st.selectbox("Select Model",
        ["Logistic Regression", "Decision Tree", "kNN", "Naive Bayes", "Random Forest", "XGBoost"])

    model_path = f"model/{model_option.replace(' ', '_').lower()}.pkl"

    if os.path.exists(model_path):
        model = joblib.load(model_path)
        y_pred = model.predict(X_test)

        # c. Display Evaluation Metrics
        st.subheader(f"Metrics for {model_option}")
        col1, col2, col3 = st.columns(3)
        col1.metric("Accuracy", round(accuracy_score(y_test, y_pred), 4))
        col2.metric("MCC", round(matthews_corrcoef(y_test, y_pred), 4))
        col3.metric("F1 Score", round(f1_score(y_test, y_pred), 4))

        # d. Confusion Matrix & Report
        st.subheader("Classification Report")
        st.text(classification_report(y_test, y_pred))

        st.subheader("Confusion Matrix")
        st.write(confusion_matrix(y_test, y_pred))
    else:
        st.error("Model file not found. Please ensure models are trained and saved in the 'model/' directory.")
